# Generated by Django 6.0.3 on 2026-03-30 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0005_alter_fotografia_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/%Y/%m/%d/'),
        ),
    ]
